repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: detect-private-key
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
